env: local
db:
  user: postgres
  password: postgres
  host: localhost
  port: 5432
  dbName: order_db
  enableSsl: false
  autoMigrate: true

server:
  name: "order-service"
  port: 8080

messagequeue:
  host: localhost:9093
  topic: payment_process_response
  consumerGroup: order-service-payment-process-response
  retry: 5
  autoCreateTopic: true

processPaymentRequest:
  host: localhost:9093
  topic: payment_process_request
  consumerGroup: order-service
  retry: 5
  autoCreateTopic: true

processPaymentResponse:
  host: localhost:9093
  topic: payment_process_response
  consumerGroup: order-service
  retry: 5
  autoCreateTopic: true

orderSuccess:
  host: localhost:9093
  topic: order_success
  consumerGroup: order-service
  retry: 5
  autoCreateTopic: true
