// Code generated by mockery v2.43.2. DO NOT EDIT.

package atomicity

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAtomicExecutor is an autogenerated mock type for the AtomicExecutor type
type MockAtomicExecutor struct {
	mock.Mock
}

type MockAtomicExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAtomicExecutor) EXPECT() *MockAtomicExecutor_Expecter {
	return &MockAtomicExecutor_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: parentCtx, executeFunc
func (_m *MockAtomicExecutor) Execute(parentCtx context.Context, executeFunc func(context.Context) error) error {
	ret := _m.Called(parentCtx, executeFunc)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(parentCtx, executeFunc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAtomicExecutor_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockAtomicExecutor_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - parentCtx context.Context
//   - executeFunc func(context.Context) error
func (_e *MockAtomicExecutor_Expecter) Execute(parentCtx interface{}, executeFunc interface{}) *MockAtomicExecutor_Execute_Call {
	return &MockAtomicExecutor_Execute_Call{Call: _e.mock.On("Execute", parentCtx, executeFunc)}
}

func (_c *MockAtomicExecutor_Execute_Call) Run(run func(parentCtx context.Context, executeFunc func(context.Context) error)) *MockAtomicExecutor_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *MockAtomicExecutor_Execute_Call) Return(_a0 error) *MockAtomicExecutor_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAtomicExecutor_Execute_Call) RunAndReturn(run func(context.Context, func(context.Context) error) error) *MockAtomicExecutor_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAtomicExecutor creates a new instance of MockAtomicExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAtomicExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAtomicExecutor {
	mock := &MockAtomicExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
