basePath: /api
definitions:
  handler.CreateOrderRequest:
    properties:
      customer_id:
        type: string
      customer_name:
        type: string
      total_amount:
        type: number
    required:
    - customer_id
    - customer_name
    - total_amount
    type: object
  handler.ErrorResponse:
    properties:
      code:
        type: integer
      error:
        type: string
    type: object
  handler.OrderResponse:
    properties:
      created_at:
        example: "2023-01-01T00:00:00Z"
        type: string
      customer_id:
        example: customer123
        type: string
      customer_name:
        example: John Doe
        type: string
      id:
        example: abc123
        type: string
      status:
        example: PENDING
        type: string
      total_amount:
        example: 99.99
        type: number
      updated_at:
        example: "2023-01-01T00:00:00Z"
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Order Service API for managing orders
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Order Service API
  version: "1.0"
paths:
  /admin/v1/orders:
    get:
      consumes:
      - application/json
      description: Retrieve all orders from the system
      produces:
      - application/json
      responses:
        "200":
          description: List of orders
          schema:
            items:
              $ref: '#/definitions/handler.OrderResponse'
            type: array
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Get all orders
      tags:
      - orders
  /admin/v1/orders/search:
    get:
      consumes:
      - application/json
      description: Search orders with filters, pagination and sorting by created_date
        or total_amount
      parameters:
      - default: 1
        description: Page number
        in: query
        minimum: 1
        name: page
        type: integer
      - default: 20
        description: Page size
        in: query
        maximum: 100
        minimum: 1
        name: page_size
        type: integer
      - default: created_at
        description: Sort by field
        enum:
        - created_at
        - total_amount
        in: query
        name: sort_by
        type: string
      - default: DESC
        description: Sort order
        enum:
        - ASC
        - DESC
        in: query
        name: sort_order
        type: string
      - description: Filter by customer ID
        in: query
        name: customer_id
        type: string
      - description: Filter by customer name
        in: query
        name: customer_name
        type: string
      - description: Filter by order status
        in: query
        name: status
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Paginated orders
          schema:
            items:
              $ref: '#/definitions/handler.OrderResponse'
            type: array
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Search orders with pagination and sorting
      tags:
      - orders
  /v1/orders:
    post:
      consumes:
      - application/json
      description: Create a new order with the provided details
      parameters:
      - description: Order information
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/handler.CreateOrderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Order created successfully
          schema:
            $ref: '#/definitions/handler.OrderResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Create a new order
      tags:
      - orders
schemes:
- http
- https
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
