basePath: /api
definitions:
  campaign.Campaign:
    properties:
      created_at:
        type: string
      description:
        type: string
      end_time:
        type: string
      id:
        type: integer
      name:
        type: string
      policy:
        $ref: '#/definitions/campaign.CampaignPolicy'
      start_time:
        type: string
      updated_at:
        type: string
    required:
    - created_at
    - description
    - end_time
    - id
    - name
    - policy
    - start_time
    - updated_at
    type: object
  campaign.CampaignPolicy:
    properties:
      max_tracked_orders:
        type: integer
      min_order_amount:
        type: integer
      total_reward:
        type: integer
    required:
    - max_tracked_orders
    - min_order_amount
    - total_reward
    type: object
  handler.CreateCampaignRequest:
    properties:
      description:
        type: string
      end_time:
        type: string
      max_tracked_orders:
        type: integer
      min_order_amount:
        type: integer
      name:
        type: string
      start_time:
        type: string
      total_reward:
        type: integer
    required:
    - description
    - end_time
    - max_tracked_orders
    - min_order_amount
    - name
    - start_time
    - total_reward
    type: object
  handler.ErrorResponse:
    properties:
      code:
        type: integer
      error:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Order Service API for managing orders
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Order Service API
  version: "1.0"
paths:
  /v1/campaigns:
    post:
      consumes:
      - application/json
      description: Create a new marketing campaign with the provided details
      parameters:
      - description: Campaign information
        in: body
        name: campaign
        required: true
        schema:
          $ref: '#/definitions/handler.CreateCampaignRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Campaign created successfully
          schema:
            $ref: '#/definitions/campaign.Campaign'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Create a new campaign
      tags:
      - campaigns
schemes:
- http
- https
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
