env: local
db:
  user: postgres
  password: postgres
  host: localhost
  port: 5434
  dbName: campaign_db
  enableSsl: false
  autoMigrate: true
  enableQueryHook: true

server:
  name: "campaign-service"
  port: 8082

kafka:
  host: localhost:9093
  retry: 5
  autoCreateTopic: true
  consumerGroup: campaign-service
  topic: notification_topic

orderConsumer:
  host: localhost:9093
  topic: order_events
  consumerGroup: campaign-order-consumer
  retry: 5
  autoCreateTopic: true

orderSuccess:
  host: localhost:9093
  topic: order_events
  consumerGroup: campaign-success-consumer
  retry: 5
  autoCreateTopic: true

iphoneCampaign: iphone

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0