// Code generated by mockery v2.43.2. DO NOT EDIT.

package database

import (
	mock "github.com/stretchr/testify/mock"
	bun "github.com/uptrace/bun"
)

// MockSelectCriteria is an autogenerated mock type for the SelectCriteria type
type MockSelectCriteria struct {
	mock.Mock
}

type MockSelectCriteria_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSelectCriteria) EXPECT() *MockSelectCriteria_Expecter {
	return &MockSelectCriteria_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *MockSelectCriteria) Execute(_a0 *bun.SelectQuery) *bun.SelectQuery {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *bun.SelectQuery
	if rf, ok := ret.Get(0).(func(*bun.SelectQuery) *bun.SelectQuery); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bun.SelectQuery)
		}
	}

	return r0
}

// MockSelectCriteria_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockSelectCriteria_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *bun.SelectQuery
func (_e *MockSelectCriteria_Expecter) Execute(_a0 interface{}) *MockSelectCriteria_Execute_Call {
	return &MockSelectCriteria_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *MockSelectCriteria_Execute_Call) Run(run func(_a0 *bun.SelectQuery)) *MockSelectCriteria_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*bun.SelectQuery))
	})
	return _c
}

func (_c *MockSelectCriteria_Execute_Call) Return(_a0 *bun.SelectQuery) *MockSelectCriteria_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSelectCriteria_Execute_Call) RunAndReturn(run func(*bun.SelectQuery) *bun.SelectQuery) *MockSelectCriteria_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSelectCriteria creates a new instance of MockSelectCriteria. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSelectCriteria(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSelectCriteria {
	mock := &MockSelectCriteria{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
