// Code generated by mockery v2.43.2. DO NOT EDIT.

package database

import (
	context "context"

	bun "github.com/uptrace/bun"

	mock "github.com/stretchr/testify/mock"
)

// MockGetDbFunc is an autogenerated mock type for the GetDbFunc type
type MockGetDbFunc struct {
	mock.Mock
}

type MockGetDbFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetDbFunc) EXPECT() *MockGetDbFunc_Expecter {
	return &MockGetDbFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx
func (_m *MockGetDbFunc) Execute(ctx context.Context) bun.IDB {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 bun.IDB
	if rf, ok := ret.Get(0).(func(context.Context) bun.IDB); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(bun.IDB)
		}
	}

	return r0
}

// MockGetDbFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockGetDbFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGetDbFunc_Expecter) Execute(ctx interface{}) *MockGetDbFunc_Execute_Call {
	return &MockGetDbFunc_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *MockGetDbFunc_Execute_Call) Run(run func(ctx context.Context)) *MockGetDbFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockGetDbFunc_Execute_Call) Return(_a0 bun.IDB) *MockGetDbFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGetDbFunc_Execute_Call) RunAndReturn(run func(context.Context) bun.IDB) *MockGetDbFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetDbFunc creates a new instance of MockGetDbFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetDbFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetDbFunc {
	mock := &MockGetDbFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
